# Generated by Django 5.1.6 on 2026-05-20 09:38

import ideas.models.idea_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='imagen',
        ),
        migrations.AddField(
            model_name='idea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='ideas/', validators=[ideas.models.idea_model.validate_file_extension, ideas.models.idea_model.validate_file_size]),
        ),
        migrations.AddField(
            model_name='idea',
            name='tipo_archivo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('video', 'Video'), ('ninguno', 'Sin archivo')], default='ninguno', max_length=20),
        ),
    ]
